<?php

use App\Brand;
use Illuminate\Database\Seeder;

class BrandsTableSeeder extends Seeder
{
    private $data = [
        1 => '4-Star',
        15 => 'Airstream',
        16 => 'Alfa',
        24 => 'American Coach',
        25 => 'American Cruiser',
        49 => 'Avion Coach',
        59 => 'Beaver',
        64 => 'Bigfoot',
        67 => 'Blue Bird',
        74 => 'Born Free',
        91 => 'Carriage',
        99 => 'Chalet',
        104 => 'Chevrolet',
        105 => 'Chinook',
        112 => 'Coach House',
        113 => 'Coachmen',
        123 => 'Country Coach',
        129 => 'CrossRoads',
        131 => 'Cruiser RV',
        140 => 'Damon',
        147 => 'Dodge',
        152 => 'DRV',
        156 => 'Dutchmen',
        157 => 'Dynamax Corp',
        167 => 'Elk Automotive',
        172 => 'EnduraMax',
        173 => 'Entegra Coach',
        180 => 'Excel',
        183 => 'Extreme',
        190 => 'Featherlite',
        200 => 'Fleetwood',
        202 => 'Ford',
        203 => 'Forest River',
        204 => 'Foretravel',
        212 => 'Franklin Coach',
        215 => 'Freightliner',
        222 => 'Georgie Boy',
        226 => 'Glendale RV',
        229 => 'GMC',
        239 => 'Gulf Stream',
        243 => 'Harney',
        249 => 'Heartland RV',
        257 => 'Holiday Rambler',
        274 => 'Host',
        285 => 'Itasca',
        287 => 'Jayco',
        296 => 'Keystone',
        305 => 'Komfort',
        308 => 'K-Z',
        313 => 'Lance',
        318 => 'Lazy Daze',
        325 => 'Leisure Travel',
        331 => "Livin' Lite",
        343 => 'Mallard Coach',
        344 => 'Mandalay',
        365 => 'Miscellaneous',
        366 => 'Mitchell Coach',
        375 => 'MVP RV',
        376 => 'National RV',
        382 => 'Newell',
        383 => 'Newmar',
        391 => 'Northwood',
        394 => 'Nu-Wa',
        399 => 'Open Range',
        400 => 'Optima',
        404 => 'Pacific Coachworks',
        406 => 'Palomino',
        417 => 'Phoenix',
        418 => 'Phoenix Cruiser',
        419 => 'Pilgrim International',
        426 => 'Pleasure-Way',
        431 => 'Prevost',
        460 => 'Rexhall',
        464 => 'Roadtrek',
        466 => 'Rockwood',
        476 => 'Safari',
        503 => 'Silver Crown',
        511 => 'Skyline',
        525 => 'Sportscoach',
        527 => 'Sportsmobile',
        550 => 'SunnyBrook',
        562 => 'Teton Homes',
        568 => 'Tiffin',
        588 => 'R-Vision',
        593 => 'Travel Supreme',
        630 => 'Weekend Warrior',
        637 => 'Western RV',
        642 => 'Winnebago',
        678 => 'Era',
        691 => 'EverGreen RV',
        737 => 'Travel Lite',
        773 => 'Cherokee',
        792 => 'Georgetown',
        838 => 'Aerolite',
        888 => 'Four Winds International',
        943 => 'Thor America',
        949 => 'Adventure',
        959 => 'Riverside',
        980 => 'Prime Time',
        993 => 'Four Winds',
        999 => 'Micro-Lite',
        1006 => 'Monaco',
        1013 => 'Chinook',
        1018 => 'Redwood Residential Vehicles',
        1020 => 'Thor CA',
        1021 => 'Thor Motor Coach',
        1185 => 'Starcraft',
        1191 => 'Thor',
        1236 => 'AMO',
        1247 => 'Coleman',
        1262 => 'Shasta',
        1282 => 'Conestoga',
        1305 => 'Yellowstone RV',
        1315 => 'Venture',
        1363 => 'Renegade',
        1372 => 'Nexus',
        1420 => 'Monaco RV',
        1429 => 'Grand Design',
        1509 => 'Midwest',
        1530 => 'Peterson',
        1567 => 'Highland Ridge',
        1611 => 'Omega RV',
        1637 => 'Regency',
    ];

    /**
     * Run the database seeds.
     */
    public function run()
    {
        foreach ($this->data as $key => $value) {
            Brand::create([
                'id' => $key,
                'name' => $value,
            ]);
        }
    }
}
